---
title: "Buble_Rladies"
output: html_document
date: "2023-07-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Grafica

```{r}
library(UpSetR)
library(dplyr)
# install.packages("UpSetR")
# github = https://github.com/hms-dbmi/UpSetR
 
# We need a data frame giving a hierarchical structure. Let's consider the flare dataset:
CCM_df<- read.csv("CMM_dataset.csv", header=T)
CCM_df<- CCM_df[,c(1:8)]

# Categorias
unique(CCM_df$Categoría)

#PRIDE
unique(CCM_df$PRIDE)

#SNI
unique(CCM_df$SNI)
```

```{r Porque no pasan el filtro}
# load library ggplot2
library(ggplot2)
 
# create sample data frame
sample_data <- data.frame(group= c('Group1', 'Group2',
                                   'Group1', 'Group2',
                                   'Group1', 'Group2'),
                          name= c('name1', 'name1',
                                  'name2', 'name2',
                                  'name3', 'name3'),
                   value= c(25,30,35,20,40,50))
 
# create nested pie chart using ggplot
ggplot(sample_data, aes(x = factor(group), y = value, fill = factor(name))) +
          geom_col() +
         scale_x_discrete(limits = c("Group1", "Group2")) +
          coord_polar("y")

# https://www.geeksforgeeks.org/nested-pie-chart-in-r/
```


```{r}
# Cargar a R los datos
CCM_df <- data.frame(
  record_ID = 1:50,
  Posicion = c(rep("Investigadores", 26), rep("Becarios Posdoctorales", 17), rep("Tecnicos academicos", 7)),
  Edad = c(
    "30-35", rep("36-40",5), rep("41-45", 4), "46-50", rep("51-55", 5), "56-60", rep("61-65",6), rep("66-70",2), "76-80", #investigadores
    "30-35", rep("36-40",5), rep("41-45", 4), rep("46-50", 3), rep("51-55", 4),  # Becarios Posdoctorales, NO SON REALES
    "25-29", "30-35", rep("36-40",2), "41-45", "46-50", "56-60" # Tecnicos academicos
           ),
  Sexo = c( rep("femenino", 4), rep("femenino", 22), #investigadores, NO SON REALES
            rep("femenino", 2), rep("femenino", 15), # Becarios Posdoctorales, NO SON REALES
            rep("femenino", 2), rep("femenino", 5) # Tecnicos academicos, NO SON REALES
            )
)

# convertir aa lista
CMM_list <- as.list(CCM_df)
```


```{r}
#install.packages("treemap")
library(treemap)
 
# Create data
group <- c("group-1","group-2","group-3")
value <- c(13,5,22)
data <- data.frame(group,value)
 
# treemap
treemap(data,
            index="group",
            vSize="value",
            type="index"
            )

treemap(CCM_df,
            index="Posicion",
            vSize="value",
            type="index"
            )
```



```{r}

# previamente se habian cargado
At_team_sense_exonic_TRANSCRIPT_IDs <- read.table("At_team_sense_exonic_IDs_ed", header= F)
At_team_NAT_TRANSCRIPT_IDs <- read.table("At_team_NAT_IDs", header= F)
At_team_lncRNAs_intergenicos_TRANSCRIPT_IDs <- read.table("At_team_lncRNAs_intergenicos_IDs_ed", header= F)
At_team_lncRNAs_intronic_TRANSCRIPT_IDs  <- read.table("At_team_lncRNAs_intronic_depurado_IDs", header= F)

# Generar una lista de conjuntos con la nueva anotacion (seccion Correccion en la anotacion de lncRNAs)

AtteamlncRNAs_listInput_newannotation_Araport11_TRANSCRIPT_IDs <- list(Araport11_NAT = c(antisense_RNA_overlap_Araport11_transcript$V1, antisense_lncRNA_overlap_Araport11_transcript$V1), Araport11_lincRNA = lnc_RNA_overlap_Araport11_transcript$V1, pseudogene = pseudogene_overlap_Araport11_transcript$V1, novel_transcribed_region = novel_transcribed_region_overlap_Araport11_transcript$V1, other_RNA = other_rna_overlap_Araport11_transcript$V1, snoRNA = snoRNA_overlap_Araport11_transcript$V1, snRNA = snRNA_overlap_Araport11_transcript$V1, protein_coding = protein_coding_overlap_Araport11_transcript$V1, NAT = At_team_NAT_TRANSCRIPT_IDs$V1, Intronic = At_team_lncRNAs_intronic_TRANSCRIPT_IDs$V1, Sense_exonic = At_team_sense_exonic_TRANSCRIPT_IDs$V1, lincRNA = At_team_lncRNAs_intergenicos_TRANSCRIPT_IDs$V1)
#View(CPC_ncd_listInput_newannotation_Araport11)

# quite los sin sentido
#Team_lncRNA_ws_intronic =At_team_lncRNAs_intronicos_SIN_sentido_IDs$V1
#Team_lncRNA_ws_exonic = At_team_lncRNAs_SIN_sentido_IDs$V1

AtteamlncRNAs_mat_overlap_Araport11_TRANSCRIPT <- fromList(AtteamlncRNAs_listInput_newannotation_Araport11_TRANSCRIPT_IDs)

# plot
tiff(file="At_team_UpsetR_annotation_keeptrue_TRANSCRIPT.tiff", width = 18, height = 10, units = 'in', res = 150)
upset(AtteamlncRNAs_mat_overlap_Araport11_TRANSCRIPT, sets = c("snRNA", "snoRNA", "pseudogene", "other_RNA", "novel_transcribed_region",  "Araport11_NAT", "protein_coding", "Araport11_lincRNA", "Intronic", "Sense_exonic", "NAT", "lincRNA"), 
      keep.order = TRUE, # mantener el orden
      order.by = "freq", # ordenar por la frecuencia
      shade.color = c("blue", "blue", "blue", "blue", "green", "green"), # color de las interacciones, el color se pone de abajo hacia arriba
      set_size.show =TRUE, # mostrar los valores en el set
      text.scale =2, # tamano de la letra, default = 1
      set_size.scale_max = 5200, #aumentar escala del set
      sets.bar.color = c("#6996b3","#6996b3","#6996b3","#6996b3","#6996b3","#6996b3","#6996b3","#6996b3", "#89a036", "#89a036", "#89a036","#89a036"),
      mainbar.y.label = "Number of transcripts", # label histograma (arriba)
      sets.x.label= "Number of transcripts") # label set (abajo)

dev.off()
```




